/*
 * Section 6 of Around the Table — "Worth the Afternoon".
 *
 * These twelve are NOT from the original recipe books. They were written to
 * fill a hole the data made obvious: across the original 225 recipes, none has
 * more than four steps, none uses yeast, and nothing asks you to knead, braise,
 * temper an egg or thicken a sauce. "In-Depth" almost always meant "leave it in
 * the slow cooker", never "this takes attention".
 *
 * Every ingredient is checked against the storehouse order list, so eleven of
 * the twelve are storehouse-only. The exception is cocoa powder, flagged as a
 * pantry extra — the storehouse carries hot cocoa mix, which is not the same
 * thing and would not work here.
 *
 * Macros are estimated from the ingredients like the rest of Around the Table,
 * and are labelled as estimates in the app.
 */

const SECTION = 'Worth the Afternoon';

module.exports = [
  {
    id: 226, book: 2, secNum: 6, secName: SECTION,
    name: 'Everyday White Bread',
    servings: '2 Loaves (24 Slices)', servN: 24,
    ing: ['5 cups white flour', '2 cups warm water', '1 packet yeast', '2 tbsp sugar',
      '3 tbsp non-fat dry milk', '2 tsp salt', '3 tbsp melted butter'],
    steps: [
      'Stir the yeast and sugar into the warm water — warm as a bath, not hot, or it will kill the yeast. Leave it 10 minutes until it foams. If nothing happens, the yeast is dead and it is worth starting again.',
      'Whisk the flour, dry milk and salt together in a large bowl.',
      'Pour in the yeast water and the melted butter. Stir until it comes together into a shaggy, untidy dough.',
      'Turn it onto a floured counter and knead 8 to 10 minutes, adding only enough flour to stop it sticking. It is ready when it is smooth and springs back when you press it.',
      'Put it in a buttered bowl, cover with a cloth, and leave somewhere warm about an hour, until doubled.',
      'Press it down, divide in two, and shape each half into a loaf. Set in buttered pans, cover, and rise again 40 minutes until domed above the rim.',
      'Bake at 375°F for 30 to 35 minutes. It is done when the top is deep gold and the bottom sounds hollow when tapped.',
      'Turn out onto a rack and let it cool before slicing. Cutting it hot tears the crumb.',
    ],
    macro: null, tagline: 'Two Loaves, One Afternoon', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 30 mins', extras: null,
  },
  {
    id: 227, book: 2, secNum: 6, secName: SECTION,
    name: 'Soft Buttered Dinner Rolls',
    servings: '15 Rolls', servN: 15,
    ing: ['4 cups white flour', '1.25 cups warm milk', '1 packet yeast', '¼ cup sugar',
      '1 egg', '¼ cup butter', '1.5 tsp salt'],
    steps: [
      'Warm the milk until it is just body temperature. Stir in the yeast and a spoonful of the sugar, and leave 10 minutes until foamy.',
      'Beat the egg with the rest of the sugar and the softened butter.',
      'Combine the flour and salt, then add both the yeast milk and the egg mixture. Mix to a soft dough.',
      'Knead 8 minutes until smooth. This dough stays softer and tackier than bread dough — resist adding much more flour.',
      'Cover and rise 1 hour until doubled.',
      'Divide into 15 pieces. Roll each into a ball under a cupped hand and set them just touching in a buttered dish.',
      'Cover and rise 35 minutes, until they are puffed and pressing against each other.',
      'Bake at 375°F for 15 to 18 minutes until golden. Brush the tops with butter the moment they come out.',
    ],
    macro: null, tagline: 'Pull-Apart Soft', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 15 mins', extras: null,
  },
  {
    id: 228, book: 2, secNum: 6, secName: SECTION,
    name: 'Cinnamon Rolls with Vanilla Glaze',
    servings: '12 Rolls', servN: 12,
    ing: ['4 cups white flour', '1 cup warm milk', '1 packet yeast', '½ cup sugar',
      '1 egg', '½ cup butter', '1 tsp salt', '½ cup brown sugar', '2 tbsp cinnamon',
      '1 cup powdered sugar', '1 tsp vanilla'],
    steps: [
      'Warm the milk, stir in the yeast and a spoonful of the sugar, and leave 10 minutes until foamy.',
      'Mix the flour, salt and half the sugar. Add the yeast milk, the egg, and half the butter, softened. Knead 8 minutes to a soft, smooth dough.',
      'Cover and rise 1 hour until doubled.',
      'Roll the dough into a rectangle about 12 by 16 inches, keeping the corners square so the rolls come out even.',
      'Spread the remaining softened butter right to the edges, then scatter over the brown sugar, the rest of the sugar, and the cinnamon.',
      'Roll it up from the long side, snug but not tight. Cut into 12 with a length of thread slid underneath and crossed over — a knife squashes them.',
      'Set cut side up in a buttered dish, cover, and rise 40 minutes until they touch.',
      'Bake at 350°F for 25 to 28 minutes until the middles are cooked through.',
      'Stir the powdered sugar with the vanilla and a spoonful of milk into a pourable glaze, and pour it over while the rolls are still warm.',
    ],
    macro: null, tagline: 'Saturday Morning, Properly', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 45 mins', extras: null,
  },
  {
    id: 229, book: 2, secNum: 6, secName: SECTION,
    name: 'Scratch Biscuits & Sausage Gravy',
    servings: '6 Servings (2 Biscuits Each)', servN: 6,
    ing: ['3 cups white flour', '4 tsp baking powder', '1 tsp salt', '½ cup cold butter',
      '1.25 cups milk', '1 lb pork sausage', '¼ cup white flour', '3 cups milk', 'black pepper'],
    steps: [
      'Rub the cold butter into the flour, baking powder and salt until it looks like coarse crumbs with some pea-sized pieces left. Cold butter is what makes the layers.',
      'Stir in the milk just until it holds together. Handle it as little as you can.',
      'Pat the dough out, fold it over on itself three times, then pat to about an inch thick and cut out 12 rounds. Press the cutter straight down — twisting seals the edge and stops the rise.',
      'Bake at 450°F for 12 to 14 minutes until risen and browned.',
      'Meanwhile, brown the sausage in a wide pan, breaking it up. Leave the fat in the pan.',
      'Sprinkle the flour over the sausage and cook it 2 minutes, stirring. This is the step people skip, and it is why gravy tastes of raw flour.',
      'Pour in the milk a splash at a time, stirring smooth after each addition.',
      'Simmer gently 5 to 8 minutes until it coats a spoon. Season well with black pepper — it needs more than you think.',
      'Split the hot biscuits and ladle the gravy over.',
    ],
    macro: null, tagline: 'Sunday Breakfast, The Long Way', score: null, sc: null,
    diff: 'In-Depth', time: '50 mins', extras: null,
  },
  {
    id: 230, book: 2, secNum: 6, secName: SECTION,
    name: 'Braised Beef with Onion Gravy',
    servings: '6 Servings', servN: 6,
    ing: ['2 lbs stewing beef', '2 onions', '2 tbsp vegetable oil', '3 tbsp white flour',
      '3 cups water', '2 lbs potatoes', '¼ cup butter', '½ cup milk', 'salt', 'black pepper'],
    steps: [
      'Pat the beef dry and salt it well. Dry meat browns; wet meat steams.',
      'Heat the oil until it shimmers and brown the beef hard on all sides, in two or three batches so the pan stays hot. Set it aside.',
      'Turn the heat down, add the sliced onions, and cook them 12 to 15 minutes until deep golden and sweet, scraping up the brown bits as they release.',
      'Sprinkle over the flour and cook 1 minute more.',
      'Pour in the water a little at a time, stirring, until you have a smooth gravy.',
      'Return the beef and any juices. Cover and cook at the barest simmer for 2½ hours, until a piece falls apart under a fork. It cannot be rushed — high heat makes it tough, not tender.',
      'Boil the potatoes 20 minutes, then mash with the butter and warmed milk.',
      'Taste the gravy and season. Spoon the beef and plenty of gravy over the mash.',
    ],
    macro: null, tagline: 'Falls Apart Under a Fork', score: null, sc: null,
    diff: 'In-Depth', time: '3 hrs 15 mins', extras: null,
  },
  {
    id: 231, book: 2, secNum: 6, secName: SECTION,
    name: 'Chicken Pot Pie with a Scratch Crust',
    servings: '6 Servings', servN: 6,
    ing: ['2.5 cups white flour', '1 tsp salt', '1 cup cold butter', '6 tbsp cold water',
      '1.5 lbs chicken breast', '1 onion', '3 carrots', '1 can green beans',
      '¼ cup white flour', '3 cups milk', 'black pepper'],
    steps: [
      'Rub the cold butter into the flour and salt, leaving some pieces the size of peas — those are what make the crust flaky.',
      'Sprinkle over the cold water and gather into a dough without kneading. Wrap and rest it in the fridge 30 minutes.',
      'Simmer the chicken in salted water 15 minutes, then lift out and cut into pieces. Keep a cup of the cooking liquid.',
      'Cook the diced onion and carrot in a little butter 8 minutes until soft.',
      'Stir in the flour and cook 1 minute, then add the milk slowly, stirring, and the reserved cup of chicken liquid.',
      'Simmer until it thickens enough to hold its shape on a spoon. Season well.',
      'Fold in the chicken and the drained green beans and tip it all into a deep dish. Let it cool a little — a hot filling melts the crust before it can set.',
      'Roll the pastry to fit, lay it over, press the edges down and cut two slits in the middle for steam.',
      'Bake at 400°F for 35 to 40 minutes until the crust is deep gold and the filling bubbles at the slits.',
    ],
    macro: null, tagline: 'The Real Thing, Not the Shortcut', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 45 mins', extras: null,
  },
  {
    id: 232, book: 2, secNum: 6, secName: SECTION,
    name: 'Peach Cobbler with a Biscuit Top',
    servings: '8 Servings', servN: 8,
    ing: ['1 can peaches (drained)', '½ cup sugar', '1 tsp cinnamon', '1 tbsp white flour',
      '1.5 cups white flour', '2 tsp baking powder', '3 tbsp sugar', '6 tbsp cold butter',
      '¾ cup milk'],
    steps: [
      'Toss the drained peaches with the sugar, cinnamon and the tablespoon of flour, along with a few spoonfuls of their syrup.',
      'Tip into a baking dish and put it in the oven at 400°F for 10 minutes, until the fruit is hot and beginning to bubble. Putting the topping on hot fruit is what cooks its underside.',
      'Meanwhile rub the cold butter into the flour, baking powder and sugar until crumbly.',
      'Stir in the milk to make a thick, shaggy batter — lumpy is right.',
      'Drop it in rough spoonfuls over the hot fruit, leaving gaps for the juice to come through.',
      'Scatter a little more sugar over the top for crunch.',
      'Bake 35 minutes more, until the topping is golden and firm in the middle and the juices bubble thickly at the edges.',
      'Let it stand 15 minutes before serving, or the juice will be thin.',
    ],
    macro: null, tagline: 'Bubbling at the Edges', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr', extras: null,
  },
  {
    id: 233, book: 2, secNum: 6, secName: SECTION,
    name: 'Baked Vanilla Custard',
    servings: '6 Servings', servN: 6,
    ing: ['4 eggs', '2.5 cups milk', '½ cup sugar', '2 tsp vanilla', 'salt', '1 tsp cinnamon'],
    steps: [
      'Heat the milk until it steams and shows a few bubbles at the edge. Do not let it boil.',
      'Whisk the eggs, sugar and a pinch of salt together until smooth but not frothy — froth turns into bubbles in the finished custard.',
      'Pour the hot milk into the eggs in a thin stream, whisking the whole time. Adding it all at once will scramble them.',
      'Pour the mixture through a sieve into a jug. This catches anything that did set and is the difference between silky and grainy.',
      'Divide between six dishes and dust the tops with cinnamon.',
      'Stand the dishes in a roasting tin and pour hot water around them to come halfway up. The water bath keeps the heat gentle and even.',
      'Bake at 325°F for 35 to 40 minutes. They are done when set at the edge and still wobbling slightly in the centre — they firm up as they cool.',
      'Lift them out of the water and chill at least 2 hours before serving.',
    ],
    macro: null, tagline: 'Silky, Set, Just Wobbling', score: null, sc: null,
    diff: 'In-Depth', time: '3 hrs', extras: null,
  },
  {
    id: 234, book: 2, secNum: 6, secName: SECTION,
    name: 'Slow Rice Pudding with Raisins',
    servings: '6 Servings', servN: 6,
    ing: ['1 cup rice', '4 cups milk', '⅓ cup sugar', '½ cup raisins', '1 egg',
      '1 tsp vanilla', '1 tsp cinnamon', 'salt'],
    steps: [
      'Simmer the rice in 2 cups of water with a pinch of salt until the water is gone, about 15 minutes.',
      'Add the milk and sugar and bring it back to the barest simmer.',
      'Cook uncovered 35 to 40 minutes, stirring often and scraping the bottom. This is the whole recipe — stirring is what makes it creamy, and leaving it will catch and scorch.',
      'Stir in the raisins for the last 10 minutes so they plump without dissolving.',
      'Beat the egg in a small bowl. Add a ladle of the hot pudding to it slowly, whisking, to warm it through.',
      'Take the pan off the heat and stir the egg mixture back in. Off the heat, or it will scramble.',
      'Stir in the vanilla and cinnamon.',
      'Let it stand 10 minutes to thicken. Good warm, better cold the next day.',
    ],
    macro: null, tagline: 'Stirred, Not Hurried', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 10 mins', extras: null,
  },
  {
    id: 235, book: 2, secNum: 6, secName: SECTION,
    name: 'Real Caramel Sauce',
    servings: '16 Servings (2 Tbsp Each)', servN: 16,
    ing: ['1 cup sugar', '¼ cup water', '6 tbsp butter', '½ cup evaporated milk', 'salt'],
    steps: [
      'Put the sugar and water in a heavy pan over medium heat and let the sugar dissolve without stirring.',
      'Once it is clear, leave it alone. Swirl the pan now and then, but do not stir — stirring makes it crystallise and go grainy.',
      'Cook 8 to 10 minutes until it turns the colour of a copper penny. Watch it closely at the end; it goes from amber to burnt in seconds.',
      'Take it off the heat and add the butter. It will bubble up hard, so stand back and use a long spoon.',
      'Warm the evaporated milk, then pour it in slowly, whisking. Cold liquid into hot sugar will seize it.',
      'Whisk in a good pinch of salt and return to low heat for a minute if any lumps remain.',
      'Cool in a jar. It thickens as it goes cold, and keeps a fortnight in the fridge.',
    ],
    macro: null, tagline: 'Copper-Penny Colour', score: null, sc: null,
    diff: 'In-Depth', time: '25 mins', extras: null,
  },
  {
    id: 236, book: 2, secNum: 6, secName: SECTION,
    name: 'Browned Butter Cocoa Brownies',
    servings: '16 Squares', servN: 16,
    ing: ['¾ cup butter', '1.25 cups sugar', '¾ cup cocoa powder', '2 eggs',
      '1 tsp vanilla', '½ tsp salt', '¾ cup white flour'],
    steps: [
      'Melt the butter in a light-coloured pan and keep cooking it. It will foam, then quieten, then the solids at the bottom will turn golden and smell of nuts — about 5 minutes. That smell is the whole point.',
      'Take it off the heat at once and whisk in the sugar, cocoa and salt while it is still hot.',
      'Let it cool 5 minutes, or the eggs will cook.',
      'Beat in the eggs one at a time, then keep beating for a full minute until the batter turns thick and glossy. That gloss is what gives brownies their papery top.',
      'Stir in the vanilla.',
      'Fold in the flour just until the last streak disappears. Any more and they turn cakey.',
      'Spread in a lined 8-inch pan and bake at 350°F for 25 minutes. A skewer should come out with moist crumbs, not clean.',
      'Cool completely in the pan before cutting. Warm brownies tear.',
    ],
    macro: null, tagline: 'Glossy Top, Fudgy Middle', score: null, sc: null,
    diff: 'In-Depth', time: '45 mins', extras: 'Cocoa Powder',
  },
  {
    id: 237, book: 2, secNum: 6, secName: SECTION,
    name: 'White Bean & Ham Soup',
    servings: '6 Servings', servN: 6,
    ing: ['2 cans great northern beans', '1 lb sliced ham', '1 onion', '3 carrots',
      '2 tbsp butter', '6 cups water', 'black pepper', 'salt'],
    steps: [
      'Dice the ham. Cook it in the butter over medium heat until the edges catch and brown — that browning is most of the flavour in a soup with this few ingredients.',
      'Add the diced onion and carrot and cook 8 minutes until softened.',
      'Pour in the water, scraping the bottom of the pot clean.',
      'Add one can of the beans, drained, and simmer gently 40 minutes.',
      'Mash the second can of beans to a rough paste and stir it in. It thickens the soup without any flour.',
      'Simmer another 10 minutes, until it has body and coats the spoon.',
      'Season with plenty of black pepper, and salt only at the end — the ham is already salty and it is easy to overshoot.',
    ],
    macro: null, tagline: 'Thickened With Its Own Beans', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 10 mins', extras: null,
  },
];
