/*
 * Section 6 of Around the Table — "Worth the Afternoon".
 *
 * These twelve are NOT from the original recipe books. They were written to
 * fill a hole the data made obvious: across the original 225 recipes, none has
 * more than four steps, none uses yeast, and nothing asks you to knead, braise,
 * temper an egg or thicken a sauce. "In-Depth" almost always meant "leave it in
 * the slow cooker", never "this takes attention".
 *
 * Every ingredient is checked against the storehouse order list, so eleven of
 * the twelve are storehouse-only. The exception is cocoa powder, flagged as a
 * pantry extra — the storehouse carries hot cocoa mix, which is not the same
 * thing and would not work here.
 *
 * Macros are estimated from the ingredients like the rest of Around the Table,
 * and are labelled as estimates in the app.
 */

const SECTION = 'Worth the Afternoon';
const COPYCAT = 'The Copycat Shelf';
const CHOC = 'For the Love of Chocolate';

module.exports = [
  {
    id: 226, book: 2, secNum: 6, secName: SECTION,
    name: 'Everyday White Bread',
    servings: '2 Loaves (24 Slices)', servN: 24,
    ing: ['5 cups white flour', '1.75 cups warm water', '1 packet yeast', '2 tbsp sugar',
      '3 tbsp non-fat dry milk', '2 tsp salt', '3 tbsp melted butter'],
    steps: [
      'Stir the yeast and sugar into the warm water — warm as a bath, not hot, or it will kill the yeast. Leave it 10 minutes until it foams. If nothing happens, the yeast is dead and it is worth starting again.',
      'Whisk the flour, dry milk and salt together in a large bowl.',
      'Pour in the yeast water and the melted butter. Stir until it comes together into a shaggy, untidy dough.',
      'Turn it onto a floured counter and knead 8 to 10 minutes, adding only enough flour to stop it sticking. It is ready when it is smooth and springs back when you press it.',
      'Put it in a buttered bowl, cover with a cloth, and leave somewhere warm about an hour, until doubled.',
      'Press it down, divide in two, and shape each half into a loaf. Set in buttered pans, cover, and rise again 40 minutes until domed above the rim.',
      'Bake at 375°F for 30 to 35 minutes. It is done when the top is deep gold and the bottom sounds hollow when tapped.',
      'Turn out onto a rack and let it cool before slicing. Cutting it hot tears the crumb.',
    ],
    macro: null, tagline: 'Two Loaves, One Afternoon', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 30 mins', extras: null,
  },
  {
    id: 227, book: 2, secNum: 6, secName: SECTION,
    name: 'Soft Buttered Dinner Rolls',
    servings: '15 Rolls', servN: 15,
    ing: ['4 cups white flour', '1.25 cups warm milk', '1 packet yeast', '¼ cup sugar',
      '1 egg', '¼ cup butter', '1.5 tsp salt'],
    steps: [
      'Warm the milk until it is just body temperature. Stir in the yeast and a spoonful of the sugar, and leave 10 minutes until foamy.',
      'Beat the egg with the rest of the sugar and the softened butter.',
      'Combine the flour and salt, then add both the yeast milk and the egg mixture. Mix to a soft dough.',
      'Knead 8 minutes until smooth. This dough stays softer and tackier than bread dough — resist adding much more flour.',
      'Cover and rise 1 hour until doubled.',
      'Divide into 15 pieces. Roll each into a ball under a cupped hand and set them just touching in a buttered dish.',
      'Cover and rise 35 minutes, until they are puffed and pressing against each other.',
      'Bake at 375°F for 15 to 18 minutes until golden. Brush the tops with butter the moment they come out.',
    ],
    macro: null, tagline: 'Pull-Apart Soft', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 15 mins', extras: null,
  },
  {
    id: 228, book: 2, secNum: 6, secName: SECTION,
    name: 'Cinnamon Rolls with Vanilla Glaze',
    servings: '12 Rolls', servN: 12,
    ing: ['4 cups white flour', '1 cup warm milk', '1 packet yeast', '½ cup sugar',
      '1 egg', '½ cup butter', '1 tsp salt', '½ cup brown sugar', '2 tbsp cinnamon',
      '1 cup powdered sugar', '1 tsp vanilla'],
    steps: [
      'Warm the milk, stir in the yeast and a spoonful of the sugar, and leave 10 minutes until foamy.',
      'Mix the flour, salt and half the sugar. Add the yeast milk, the egg, and half the butter, softened. Knead 8 minutes to a soft, smooth dough.',
      'Cover and rise 1 hour until doubled.',
      'Roll the dough into a rectangle about 12 by 16 inches, keeping the corners square so the rolls come out even.',
      'Spread the remaining softened butter right to the edges, then scatter over the brown sugar, the rest of the sugar, and the cinnamon.',
      'Roll it up from the long side, snug but not tight. Cut into 12 with a length of thread slid underneath and crossed over — a knife squashes them.',
      'Set cut side up in a buttered dish, cover, and rise 40 minutes until they touch.',
      'Bake at 350°F for 25 to 28 minutes until the middles are cooked through.',
      'Stir the powdered sugar with the vanilla and a spoonful of milk into a pourable glaze, and pour it over while the rolls are still warm.',
    ],
    macro: null, tagline: 'Saturday Morning, Properly', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 45 mins', extras: null,
  },
  {
    id: 229, book: 2, secNum: 6, secName: SECTION,
    name: 'Scratch Biscuits & Sausage Gravy',
    servings: '6 Servings (2 Biscuits Each)', servN: 6,
    ing: ['3 cups white flour', '4 tsp baking powder', '1 tsp salt', '½ cup cold butter',
      '1.25 cups milk', '1 lb pork sausage', '¼ cup white flour', '3 cups milk', 'black pepper'],
    steps: [
      'Rub the cold butter into the flour, baking powder and salt until it looks like coarse crumbs with some pea-sized pieces left. Cold butter is what makes the layers.',
      'Stir in the milk just until it holds together. Handle it as little as you can.',
      'Pat the dough out, fold it over on itself three times, then pat to about an inch thick and cut out 12 rounds. Press the cutter straight down — twisting seals the edge and stops the rise.',
      'Bake at 450°F for 12 to 14 minutes until risen and browned.',
      'Meanwhile, brown the sausage in a wide pan, breaking it up. Leave the fat in the pan.',
      'Sprinkle the flour over the sausage and cook it 2 minutes, stirring. This is the step people skip, and it is why gravy tastes of raw flour.',
      'Pour in the milk a splash at a time, stirring smooth after each addition.',
      'Simmer gently 5 to 8 minutes until it coats a spoon. Season well with black pepper — it needs more than you think.',
      'Split the hot biscuits and ladle the gravy over.',
    ],
    macro: null, tagline: 'Sunday Breakfast, The Long Way', score: null, sc: null,
    diff: 'In-Depth', time: '50 mins', extras: null,
  },
  {
    id: 230, book: 2, secNum: 6, secName: SECTION,
    name: 'Braised Beef with Onion Gravy',
    servings: '6 Servings', servN: 6,
    ing: ['2 lbs stewing beef', '2 onions', '2 tbsp vegetable oil', '3 tbsp white flour',
      '3 cups water', '2 lbs potatoes', '¼ cup butter', '½ cup milk', 'salt', 'black pepper'],
    steps: [
      'Pat the beef dry and salt it well. Dry meat browns; wet meat steams.',
      'Heat the oil until it shimmers and brown the beef hard on all sides, in two or three batches so the pan stays hot. Set it aside.',
      'Turn the heat down, add the sliced onions, and cook them 12 to 15 minutes until deep golden and sweet, scraping up the brown bits as they release.',
      'Sprinkle over the flour and cook 1 minute more.',
      'Pour in the water a little at a time, stirring, until you have a smooth gravy.',
      'Return the beef and any juices. Cover and cook at the barest simmer for 2½ hours, until a piece falls apart under a fork. It cannot be rushed — high heat makes it tough, not tender.',
      'Boil the potatoes 20 minutes, then mash with the butter and warmed milk.',
      'Taste the gravy and season. Spoon the beef and plenty of gravy over the mash.',
    ],
    macro: null, tagline: 'Falls Apart Under a Fork', score: null, sc: null,
    diff: 'In-Depth', time: '3 hrs 15 mins', extras: null,
  },
  {
    id: 231, book: 2, secNum: 6, secName: SECTION,
    name: 'Chicken Pot Pie with a Scratch Crust',
    servings: '6 Servings', servN: 6,
    ing: ['2.5 cups white flour', '1 tsp salt', '1 cup cold butter', '6 tbsp cold water',
      '1.5 lbs chicken breast', '1 onion', '3 carrots', '1 can green beans',
      '¼ cup white flour', '3 cups milk', 'black pepper'],
    steps: [
      'Rub the cold butter into the flour and salt, leaving some pieces the size of peas — those are what make the crust flaky.',
      'Sprinkle over the cold water and gather into a dough without kneading. Wrap and rest it in the fridge 30 minutes.',
      'Simmer the chicken in salted water about 15 minutes, until it is no longer pink in the middle, then lift out and cut into pieces. Keep a cup of the cooking liquid.',
      'Cook the diced onion and carrot in a little butter 8 minutes until soft.',
      'Stir in the flour and cook 1 minute, then add the milk slowly, stirring, and the reserved cup of chicken liquid.',
      'Simmer until it thickens enough to hold its shape on a spoon. Season well.',
      'Fold in the chicken and the drained green beans and tip it all into a deep dish. Let it cool a little — a hot filling melts the crust before it can set.',
      'Roll the pastry to fit, lay it over, press the edges down and cut two slits in the middle for steam.',
      'Bake at 400°F for 35 to 40 minutes until the crust is deep gold and the filling bubbles at the slits.',
    ],
    macro: null, tagline: 'The Real Thing, Not the Shortcut', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 45 mins', extras: null,
  },
  {
    id: 232, book: 2, secNum: 6, secName: SECTION,
    name: 'Peach Cobbler with a Biscuit Top',
    servings: '8 Servings', servN: 8,
    ing: ['1 can peaches (drained)', '½ cup sugar', '1 tsp cinnamon', '1 tbsp white flour',
      '1.5 cups white flour', '2 tsp baking powder', '3 tbsp sugar', '6 tbsp cold butter',
      '¾ cup milk'],
    steps: [
      'Toss the drained peaches with the sugar, cinnamon and the tablespoon of flour, along with a few spoonfuls of their syrup.',
      'Tip into a baking dish and put it in the oven at 400°F for 10 minutes, until the fruit is hot and beginning to bubble. Putting the topping on hot fruit is what cooks its underside.',
      'Meanwhile rub the cold butter into the flour, baking powder and sugar until crumbly.',
      'Stir in the milk to make a thick, shaggy batter — lumpy is right.',
      'Drop it in rough spoonfuls over the hot fruit, leaving gaps for the juice to come through.',
      'Scatter a little more sugar over the top for crunch.',
      'Bake 35 minutes more, until the topping is golden and firm in the middle and the juices bubble thickly at the edges.',
      'Let it stand 15 minutes before serving, or the juice will be thin.',
    ],
    macro: null, tagline: 'Bubbling at the Edges', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr', extras: null,
  },
  {
    id: 233, book: 2, secNum: 6, secName: SECTION,
    name: 'Baked Vanilla Custard',
    servings: '6 Servings', servN: 6,
    ing: ['4 eggs', '2.5 cups milk', '½ cup sugar', '2 tsp vanilla', 'salt', '1 tsp cinnamon'],
    steps: [
      'Heat the milk until it steams and shows a few bubbles at the edge. Do not let it boil.',
      'Whisk the eggs, sugar and a pinch of salt together until smooth but not frothy — froth turns into bubbles in the finished custard.',
      'Pour the hot milk into the eggs in a thin stream, whisking the whole time. Adding it all at once will scramble them.',
      'Pour the mixture through a sieve into a jug. This catches anything that did set and is the difference between silky and grainy.',
      'Divide between six dishes and dust the tops with cinnamon.',
      'Stand the dishes in a roasting tin and pour hot water around them to come halfway up. The water bath keeps the heat gentle and even.',
      'Bake at 325°F for 35 to 40 minutes. They are done when set at the edge and still wobbling slightly in the centre — they firm up as they cool.',
      'Lift them out of the water and chill at least 2 hours before serving.',
    ],
    macro: null, tagline: 'Silky, Set, Just Wobbling', score: null, sc: null,
    diff: 'In-Depth', time: '3 hrs', extras: null,
  },
  {
    id: 234, book: 2, secNum: 6, secName: SECTION,
    name: 'Slow Rice Pudding with Raisins',
    servings: '6 Servings', servN: 6,
    ing: ['1 cup rice', '4 cups milk', '⅓ cup sugar', '½ cup raisins', '2 eggs',
      '1 tsp vanilla', '1 tsp cinnamon', 'salt'],
    steps: [
      'Simmer the rice in 2 cups of water with a pinch of salt until the water is gone, about 15 minutes.',
      'Add the milk and sugar and bring it back to the barest simmer.',
      'Cook uncovered 35 to 40 minutes, stirring often and scraping the bottom. This is the whole recipe — stirring is what makes it creamy, and leaving it will catch and scorch.',
      'Stir in the raisins for the last 10 minutes so they plump without dissolving.',
      'Beat the eggs in a small bowl. Add a ladle of the hot pudding to them slowly, whisking, to warm them through.',
      'Take the pan off the heat and stir the egg mixture back in. Off the heat, or it will scramble.',
      'Stir in the vanilla and cinnamon.',
      'Let it stand 10 minutes to thicken. Good warm, better cold the next day.',
    ],
    macro: null, tagline: 'Stirred, Not Hurried', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 10 mins', extras: null,
  },
  {
    id: 235, book: 2, secNum: 6, secName: SECTION,
    name: 'Real Caramel Sauce',
    servings: '16 Servings (2 Tbsp Each)', servN: 16,
    ing: ['1 cup sugar', '¼ cup water', '6 tbsp butter', '½ cup evaporated milk', 'salt'],
    steps: [
      'Put the sugar and water in a heavy pan over medium heat and let the sugar dissolve without stirring.',
      'Once it is clear, leave it alone. Swirl the pan now and then, but do not stir — stirring makes it crystallise and go grainy.',
      'Cook 8 to 10 minutes until it turns the colour of a copper penny. Watch it closely at the end; it goes from amber to burnt in seconds.',
      'Take it off the heat and add the butter. It will bubble up hard, so stand back and use a long spoon.',
      'Warm the evaporated milk, then pour it in slowly, whisking. Cold liquid into hot sugar will seize it.',
      'Whisk in a good pinch of salt and return to low heat for a minute if any lumps remain.',
      'Cool in a jar. It thickens as it goes cold, and keeps a fortnight in the fridge.',
    ],
    macro: null, tagline: 'Copper-Penny Colour', score: null, sc: null,
    diff: 'In-Depth', time: '25 mins', extras: null,
  },
  {
    id: 236, book: 2, secNum: 6, secName: SECTION,
    name: 'Browned Butter Cocoa Brownies',
    servings: '16 Squares', servN: 16,
    ing: ['¾ cup butter', '1.25 cups sugar', '¾ cup cocoa powder', '2 eggs',
      '1 tsp vanilla', '½ tsp salt', '¾ cup white flour'],
    steps: [
      'Melt the butter in a light-coloured pan and keep cooking it. It will foam, then quieten, then the solids at the bottom will turn golden and smell of nuts — about 5 minutes. That smell is the whole point.',
      'Take it off the heat at once and whisk in the sugar, cocoa and salt while it is still hot.',
      'Let it cool 5 minutes, or the eggs will cook.',
      'Beat in the eggs one at a time, then keep beating for a full minute until the batter turns thick and glossy. That gloss is what gives brownies their papery top.',
      'Stir in the vanilla.',
      'Fold in the flour just until the last streak disappears. Any more and they turn cakey.',
      'Spread in a lined 8-inch pan and bake at 350°F for 25 minutes. A skewer should come out with moist crumbs, not clean.',
      'Cool completely in the pan before cutting. Warm brownies tear.',
    ],
    macro: null, tagline: 'Glossy Top, Fudgy Middle', score: null, sc: null,
    diff: 'In-Depth', time: '45 mins', extras: 'Cocoa Powder',
  },
  {
    id: 237, book: 2, secNum: 6, secName: SECTION,
    name: 'White Bean & Ham Soup',
    servings: '6 Servings', servN: 6,
    ing: ['2 cans great northern beans', '1 lb sliced ham', '1 onion', '3 carrots',
      '2 tbsp butter', '6 cups water', 'black pepper', 'salt'],
    steps: [
      'Dice the ham. Cook it in the butter over medium heat until the edges catch and brown — that browning is most of the flavour in a soup with this few ingredients.',
      'Add the diced onion and carrot and cook 8 minutes until softened.',
      'Pour in the water, scraping the bottom of the pot clean.',
      'Add one can of the beans, drained, and simmer gently 40 minutes.',
      'Mash the second can of beans to a rough paste and stir it in. It thickens the soup without any flour.',
      'Simmer another 10 minutes, until it has body and coats the spoon.',
      'Season with plenty of black pepper, and salt only at the end — the ham is already salty and it is easy to overshoot.',
    ],
    macro: null, tagline: 'Thickened With Its Own Beans', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 10 mins', extras: null,
  },

  // ======================= The Copycat Shelf ==============================
  {
    id: 238, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Sweet Pork Barbacoa, Cafe Rio Style',
    servings: '10 Servings', servN: 10,
    ing: ['3 lbs pork roast', '1 cup cola', '1 cup brown sugar', '1 cup salsa',
      '2 tsp chili powder', '1 tsp ground cumin', '2 tsp salt', '1 tbsp vegetable oil'],
    steps: [
      'Cut the pork into large chunks and pat them dry. Salt them well and leave them 20 minutes while the oven heats.',
      'Brown the chunks hard in the oil, in batches. Do not crowd the pan — this browning is where the depth comes from and you cannot get it back later.',
      'Put the pork in a slow cooker with half the cola and cook on low 6 hours, until it shreds under a fork.',
      'Drain off and discard the cooking liquid. This is the step that separates the good version from the greasy one.',
      'Shred the meat with two forks and return it to the pot.',
      'Blend the remaining cola, brown sugar, salsa, chili powder and cumin, and pour it over.',
      'Cook another hour on low, uncovered for the last 20 minutes so the sauce tightens and clings.',
      'Taste for salt. Serve in tortillas, over rice, or in a bowl with beans and lettuce.',
    ],
    macro: null, tagline: 'The One Everyone Asks For', score: null, sc: null,
    diff: 'In-Depth', time: '7 hrs 30 mins', extras: 'Cola, Chili Powder, Cumin',
  },
  {
    id: 239, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Cilantro Lime Rice',
    servings: '8 Servings', servN: 8,
    ing: ['2 cups rice', '4 cups water', '2 tbsp butter', '2 tsp salt', '1 lime', 'cilantro'],
    steps: [
      'Rinse the rice under cold water until the water runs clear. Rinsing is what stops it going sticky.',
      'Melt the butter in the pan and stir the drained rice through it for 2 minutes, until the grains look glassy at the edges.',
      'Add the water and salt, bring to a boil, then turn it to the lowest heat and cover.',
      'Cook 18 minutes without lifting the lid, then take it off the heat and leave it covered another 10.',
      'Fluff with a fork, then fold through the juice of the lime and a good handful of chopped cilantro.',
      'Both go in at the end — cooked lime turns bitter and cooked cilantro turns to nothing.',
    ],
    macro: null, tagline: 'Green, Bright, Never Sticky', score: null, sc: null,
    diff: 'Medium', time: '40 mins', extras: 'Lime, Cilantro',
  },
  {
    id: 240, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Creamy Tomatillo Ranch Dressing',
    servings: '12 Servings (2 Tbsp Each)', servN: 12,
    ing: ['1 cup ranch dressing', '½ cup salsa verde', '¼ cup milk', '1 lime', 'cilantro',
      '1 clove garlic'],
    steps: [
      'Put the ranch, salsa verde and milk in a jug.',
      'Add the juice of the lime, a large handful of cilantro and the peeled garlic clove.',
      'Blend until it is completely smooth and pale green.',
      'Thin with a little more milk if it is thicker than pouring cream.',
      'Chill at least an hour before serving — it tastes sharp and disjointed straight away and comes together cold.',
    ],
    macro: null, tagline: 'The Green Dressing', score: null, sc: null,
    diff: 'Easy', time: '1 hr 10 mins', extras: 'Salsa Verde, Lime, Cilantro, Garlic',
  },
  {
    id: 241, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Crispy Buttermilk Fried Chicken',
    servings: '6 Servings', servN: 6,
    ing: ['3 lbs chicken breasts', '2 cups buttermilk', '3 cups white flour', '2 eggs',
      '2 tbsp paprika', '1 tbsp garlic powder', '1 tbsp onion powder', '2 tsp black pepper',
      '1 tsp dried thyme', '1 tsp dried oregano', '1 tsp mustard powder', '1 tbsp salt',
      '4 cups vegetable oil (for frying)'],
    steps: [
      'Cut the chicken into pieces and soak them in the buttermilk for at least 4 hours, or overnight. This is what makes it tender all the way through.',
      'Mix the flour with the paprika, garlic powder, onion powder, pepper, thyme, oregano, mustard powder and salt. Rub the mixture between your fingers so the spices spread evenly.',
      'Beat the eggs with a splash of the buttermilk in a second bowl.',
      'Lift each piece out of the buttermilk, into the flour, into the egg, then back into the flour. The double coat is where the craggy crust comes from.',
      'Let the coated pieces sit 15 minutes. If you fry them straight away the coating slides off.',
      'Heat the oil to 325°F in a deep heavy pan, no more than a third full. Keep a lid nearby.',
      'Fry in small batches 12 to 15 minutes, turning once, until deep gold. Crowding the pan drops the temperature and gives you greasy chicken.',
      'Check the thickest piece reads 165°F inside, then drain on a rack, not on paper — paper steams the bottom soft.',
      'Salt the moment it comes out of the oil.',
    ],
    macro: null, tagline: 'Craggy, Golden, Worth the Mess', score: null, sc: null,
    diff: 'In-Depth', time: '5 hrs', extras: 'Paprika, Garlic Powder, Onion Powder, Thyme, Oregano, Mustard Powder',
  },
  {
    id: 242, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Steakhouse Rolls with Cinnamon Honey Butter',
    servings: '18 Rolls', servN: 18,
    ing: ['4.5 cups white flour', '1.25 cups warm milk', '1 packet yeast', '⅓ cup sugar',
      '1 egg', '¼ cup butter', '2 tsp salt', '½ cup butter', '¼ cup honey',
      '¼ cup powdered sugar', '1 tsp cinnamon'],
    steps: [
      'Warm the milk to blood heat, stir in the yeast and a spoonful of the sugar, and leave 10 minutes until foamy.',
      'Mix in the egg, the remaining sugar, the quarter cup of melted butter and the salt.',
      'Add the flour a cup at a time until you have a soft dough, then knead 8 minutes until smooth.',
      'Cover and rise 1 hour until doubled.',
      'Roll out to half an inch thick and cut into squares — square is the shape that makes these recognisable.',
      'Set them on a tray with room to spread, cover, and rise 45 minutes.',
      'Bake at 350°F for 12 to 14 minutes, only until barely golden. Overbaked, they lose the pillowy middle.',
      'Beat the half cup of soft butter with the honey, powdered sugar and cinnamon until light and whipped.',
      'Brush the hot rolls with butter and serve with the honey butter alongside.',
    ],
    macro: null, tagline: 'Square, Pillowy, Dangerous', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 30 mins', extras: null,
  },
  {
    id: 243, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Sticky Finger Sauce',
    servings: '10 Servings (2 Tbsp Each)', servN: 10,
    ing: ['⅔ cup hot sauce', '1.5 cups brown sugar', '2 tbsp water'],
    steps: [
      'Stir the hot sauce, brown sugar and water together in a small pan.',
      'Bring it to a simmer over medium heat, stirring until the sugar has completely dissolved.',
      'Simmer 4 to 5 minutes until it thickens enough to coat the back of a spoon.',
      'Take it off the heat and let it cool slightly — it thickens more as it stands.',
      'Toss it through hot fried chicken pieces just before serving, so the coating stays crisp underneath.',
    ],
    macro: null, tagline: 'Sweet, Hot, Sticky', score: null, sc: null,
    diff: 'Easy', time: '12 mins', extras: 'Hot Sauce',
  },
  {
    id: 244, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Thick Diner-Style Chili',
    servings: '8 Servings', servN: 8,
    ing: ['2 lbs ground beef', '1 onion', '1 can diced tomatoes', '2 cans tomato sauce',
      '1 can pinto beans', '1 can black beans', '3 carrots', '2 tbsp chili powder',
      '1 tsp ground cumin', '2 cups water', 'salt', 'black pepper'],
    steps: [
      'Brown the ground beef in a large pot, breaking it up small. Drain off the fat.',
      'Add the diced onion and grated carrot and cook 8 minutes until soft. The carrot is the secret — it sweetens the chili without any sugar.',
      'Stir in the chili powder and cumin and cook 1 minute, until they smell toasted rather than dusty.',
      'Add the diced tomatoes, tomato sauce and water and bring to a simmer.',
      'Simmer uncovered 45 minutes, stirring now and then, until it has darkened and thickened.',
      'Add both cans of drained beans and simmer another 15 minutes.',
      'Season with salt and plenty of black pepper. It is better the next day, and better again the day after.',
    ],
    macro: null, tagline: 'Better the Next Day', score: null, sc: null,
    diff: 'Medium', time: '1 hr 20 mins', extras: 'Chili Powder, Cumin',
  },
  {
    id: 245, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Country Store Hash Brown Casserole',
    servings: '10 Servings', servN: 10,
    ing: ['3 lbs potatoes', '2 cups cheddar', '1 cup sour cream', '1 can cream of chicken soup',
      '½ cup butter', '1 onion', '1 tsp salt', 'black pepper'],
    steps: [
      'Grate the potatoes coarsely, then squeeze them dry in a clean cloth. Wet potato steams instead of browning and the casserole goes watery.',
      'Melt the butter and stir it through the potatoes with the finely diced onion.',
      'Mix in the sour cream, the soup, half the cheese, the salt and plenty of pepper.',
      'Spread it into a buttered dish without pressing it down — you want air in it.',
      'Scatter the remaining cheese over the top.',
      'Bake at 350°F for 50 minutes, until it is bubbling at the edges and the top is deeply browned.',
      'Rest 10 minutes before serving so it holds together on the spoon.',
    ],
    macro: null, tagline: 'The Casserole People Ask About', score: null, sc: null,
    diff: 'Medium', time: '1 hr 15 mins', extras: null,
  },
  {
    id: 246, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Pickle-Brined Chicken Sandwiches',
    servings: '6 Sandwiches', servN: 6,
    ing: ['2 lbs chicken breasts', '1 cup pickle juice', '1 cup white flour', '1 egg',
      '½ cup milk', '2 tsp paprika', '1 tsp black pepper', '2 tsp salt',
      '3 cups vegetable oil (for frying)', '6 hamburger buns', '2 tbsp butter'],
    steps: [
      'Slice the chicken breasts flat and pound them to an even thickness so they cook through at the same rate.',
      'Soak them in the pickle juice for 1 hour. Longer than two and the texture turns rubbery.',
      'Beat the egg with the milk. Mix the flour with the paprika, pepper and salt.',
      'Dip each piece in the egg, then press it firmly into the seasoned flour.',
      'Heat the oil to 350°F in a heavy pan.',
      'Fry 3 to 4 minutes a side until deep gold and cooked through, then drain on a rack.',
      'Butter the cut side of the buns and toast them face down in a dry pan until golden — the buttered toast is what keeps the bun from going soggy.',
      'Build with two pickle slices and nothing else. That is the whole point of it.',
    ],
    macro: null, tagline: 'Two Pickles, Nothing Else', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 40 mins', extras: 'Pickle Juice, Paprika',
  },
  {
    id: 247, book: 2, secNum: 7, secName: COPYCAT,
    name: 'Honey Mustard Dipping Sauce',
    servings: '8 Servings (2 Tbsp Each)', servN: 8,
    ing: ['½ cup mayo', '2 tbsp honey', '1 tbsp mustard', '2 tbsp BBQ sauce'],
    steps: [
      'Whisk the mayo and honey together until completely smooth.',
      'Add the mustard and the barbecue sauce and whisk again.',
      'Taste it. It should be sweet first, tangy second, smoky underneath — adjust with a little more honey or mustard.',
      'Chill 30 minutes before serving.',
    ],
    macro: null, tagline: 'Sweet First, Tangy Second', score: null, sc: null,
    diff: 'Easy', time: '35 mins', extras: 'BBQ Sauce',
  },

  // ==================== For the Love of Chocolate =========================
  {
    id: 248, book: 2, secNum: 8, secName: CHOC,
    name: 'Thick Bakery-Style Chocolate Chip Cookies',
    servings: '12 Large Cookies', servN: 12,
    ing: ['1 cup butter', '1 cup brown sugar', '½ cup sugar', '2 eggs', '2 tsp vanilla',
      '3 cups white flour', '1 tbsp cornstarch', '1 tsp baking soda', '1 tsp salt',
      '2 cups chocolate chips'],
    steps: [
      'Beat the cold butter with both sugars for a full 3 minutes, until pale and fluffy. Cold butter is what keeps these thick instead of spreading flat.',
      'Beat in the eggs one at a time, then the vanilla.',
      'Whisk the flour, cornstarch, baking soda and salt together. The cornstarch is the whole trick — it makes the middle soft and slightly underdone-looking.',
      'Fold the dry into the wet just until the last streak of flour disappears. Overmixing builds gluten and makes them tough.',
      'Fold in the chocolate chips.',
      'Divide into 12 large mounds, roughly 4 oz each, and pile them tall rather than flattening them.',
      'Chill the mounds at least 2 hours, or overnight. Skipping this is the single most common reason cookies come out flat and greasy.',
      'Bake at 400°F for 10 to 12 minutes. Pull them when the edges are set and the middles still look wet and underbaked.',
      'Leave them on the hot tray 10 minutes to finish cooking through, then move to a rack.',
    ],
    macro: null, tagline: 'Tall, Craggy, Molten Middle', score: null, sc: null,
    diff: 'In-Depth', time: '2 hrs 45 mins', extras: 'Chocolate Chips, Cornstarch',
  },
  {
    id: 249, book: 2, secNum: 8, secName: CHOC,
    name: 'Molten Chocolate Lava Cakes',
    servings: '6 Cakes', servN: 6,
    ing: ['1 cup chocolate chips', '½ cup butter', '3 eggs', '½ cup powdered sugar',
      '¼ cup white flour', '1 tsp vanilla', 'salt'],
    steps: [
      'Butter six ramekins heavily and dust them with sugar. Anything less and the cakes will not turn out.',
      'Melt the chocolate chips and butter together over a pan of barely simmering water, stirring until glossy. Do not let the bowl touch the water or the chocolate will seize.',
      'Whisk the eggs with the powdered sugar and a pinch of salt for 2 minutes, until thick and pale.',
      'Fold the warm chocolate into the eggs, then fold in the flour and vanilla.',
      'Divide between the ramekins and chill 30 minutes. You can hold them here for a day.',
      'Bake at 425°F for 11 to 13 minutes. The edges should be set and the centre should still wobble like a jelly.',
      'This is a recipe about timing, not doneness. A minute too long and you have a very good small chocolate cake and no lava.',
      'Rest 1 minute, run a knife round the edge, and turn out onto plates. Serve at once.',
    ],
    macro: null, tagline: 'A Minute Too Long and It Is Just Cake', score: null, sc: null,
    diff: 'In-Depth', time: '55 mins', extras: 'Chocolate Chips',
  },
  {
    id: 250, book: 2, secNum: 8, secName: CHOC,
    name: 'Chocolate Sheet Cake with Fudge Icing',
    servings: '20 Servings', servN: 20,
    ing: ['2 cups white flour', '2 cups sugar', '1 cup butter', '¼ cup cocoa powder',
      '1 cup water', '½ cup sour cream', '2 eggs', '1 tsp baking soda', '1 tsp salt',
      '½ cup butter', '¼ cup cocoa powder', '6 tbsp milk', '4 cups powdered sugar',
      '1 tsp vanilla'],
    steps: [
      'Whisk the flour, sugar and salt together in a large bowl.',
      'Bring the cup of butter, the quarter cup of cocoa and the water to a boil in a pan, then pour it over the flour mixture and stir smooth.',
      'Beat in the sour cream, eggs and baking soda.',
      'Pour into a greased sheet pan — the batter will be thin, which is correct.',
      'Bake at 350°F for 20 minutes, until a skewer comes out clean.',
      'While it bakes, make the icing: boil the half cup of butter, the second quarter cup of cocoa and the milk together.',
      'Take it off the heat and beat in the powdered sugar and vanilla until pourable and glossy.',
      'Pour the icing over the cake while both are still hot. This is the entire point of the recipe — hot icing on hot cake soaks in and sets to a fudgy shell.',
      'Leave to set at least an hour before cutting.',
    ],
    macro: null, tagline: 'Hot Icing, Hot Cake', score: null, sc: null,
    diff: 'In-Depth', time: '1 hr 45 mins', extras: 'Cocoa Powder',
  },
  {
    id: 251, book: 2, secNum: 8, secName: CHOC,
    name: 'Hot Fudge Sauce',
    servings: '12 Servings (2 Tbsp Each)', servN: 12,
    ing: ['½ cup butter', '⅔ cup cocoa powder', '1.5 cups sugar', '1 cup evaporated milk',
      '1 tsp vanilla', 'salt'],
    steps: [
      'Melt the butter in a heavy pan over low heat.',
      'Whisk in the cocoa and cook it 1 minute — cooking the cocoa in fat is what takes the raw, dusty edge off it.',
      'Add the sugar and evaporated milk and stir until the sugar has dissolved completely. Rub a little between your fingers to check for grit.',
      'Bring to a gentle simmer and cook 6 to 8 minutes, stirring, until it thickens and coats a spoon heavily.',
      'Take it off the heat and stir in the vanilla and a pinch of salt.',
      'Serve hot. It thickens to a spoonable fudge in the fridge and keeps two weeks — warm it gently to pour again.',
    ],
    macro: null, tagline: 'Thick Enough to Coat a Spoon', score: null, sc: null,
    diff: 'Medium', time: '20 mins', extras: 'Cocoa Powder',
  },
  {
    id: 252, book: 2, secNum: 8, secName: CHOC,
    name: 'No-Bake Chocolate Oat Cookies',
    servings: '24 Cookies', servN: 24,
    ing: ['2 cups sugar', '½ cup butter', '½ cup milk', '¼ cup cocoa powder',
      '½ cup peanut butter', '3 cups rolled oats', '1 tsp vanilla', 'salt'],
    steps: [
      'Put the sugar, butter, milk and cocoa in a pan and bring to a rolling boil, stirring.',
      'Boil for exactly 1 minute, timed. Under-boiled and they never set; over-boiled and they turn dry and crumbly. This one minute is the whole recipe.',
      'Take it off the heat and stir in the peanut butter and vanilla until smooth.',
      'Stir in the oats and a pinch of salt, working quickly before it starts to set.',
      'Drop spoonfuls onto waxed paper.',
      'Leave them to set at room temperature about 30 minutes. Do not put them in the fridge, which makes them sweat.',
    ],
    macro: null, tagline: 'Boil One Minute, Exactly', score: null, sc: null,
    diff: 'Easy', time: '40 mins', extras: 'Cocoa Powder',
  },
  {
    id: 253, book: 2, secNum: 8, secName: CHOC,
    name: 'Peanut Butter Buckeyes',
    servings: '36 Pieces', servN: 36,
    ing: ['1.5 cups peanut butter', '½ cup butter', '4 cups powdered sugar', '1 tsp vanilla',
      '2 cups chocolate chips'],
    steps: [
      'Beat the peanut butter with the softened butter and vanilla until smooth.',
      'Work in the powdered sugar a cup at a time until you have a stiff dough that holds its shape.',
      'Roll into balls and set them on a tray. Push a toothpick into each one.',
      'Chill 1 hour until firm. Soft balls fall off the stick straight into the chocolate.',
      'Melt the chocolate chips gently over barely simmering water, stirring until glossy.',
      'Hold each ball by its toothpick and dip it into the chocolate, leaving a circle of peanut butter showing at the top — that bare circle is what makes it a buckeye.',
      'Set back on the tray, smooth over the toothpick hole with a fingertip, and chill until firm.',
    ],
    macro: null, tagline: 'The Bare Circle on Top', score: null, sc: null,
    diff: 'Medium', time: '1 hr 45 mins', extras: 'Chocolate Chips',
  },
  {
    id: 254, book: 2, secNum: 8, secName: CHOC,
    name: 'Old-Fashioned Chocolate Fudge',
    servings: '36 Squares', servN: 36,
    ing: ['3 cups sugar', '1 cup evaporated milk', '½ cup butter', '2 cups chocolate chips',
      '1 tsp vanilla', 'salt'],
    steps: [
      'Butter a square pan and line it with a strip of parchment hanging over two sides.',
      'Bring the sugar, evaporated milk and butter to a boil in a heavy pan, stirring constantly.',
      'Boil 5 minutes, still stirring, without letting it catch. Scorched fudge cannot be rescued.',
      'Take it off the heat and tip in the chocolate chips, vanilla and a pinch of salt.',
      'Stir until every chip has melted and the mixture turns thick, glossy and loses its shine at the edges.',
      'Pour into the pan at once and spread it level — it begins setting immediately.',
      'Leave at room temperature 3 hours to set, then lift out and cut into small squares. It is rich enough that small is the right size.',
    ],
    macro: null, tagline: 'Rich Enough That Small Is Right', score: null, sc: null,
    diff: 'In-Depth', time: '3 hrs 30 mins', extras: 'Chocolate Chips',
  },
  {
    id: 255, book: 2, secNum: 8, secName: CHOC,
    name: 'Chocolate Chip Banana Bread',
    servings: '12 Slices', servN: 12,
    ing: ['3 ripe bananas', '½ cup butter', '¾ cup brown sugar', '2 eggs', '1 tsp vanilla',
      '1.75 cups white flour', '1 tsp baking soda', '1 tsp salt', '1 cup chocolate chips'],
    steps: [
      'Mash the bananas well. They should be heavily freckled or nearly black — underripe bananas make bland bread.',
      'Melt the butter and beat it with the brown sugar.',
      'Beat in the eggs and vanilla, then the mashed banana.',
      'Whisk the flour, baking soda and salt together, then fold them in just until combined.',
      'Toss the chocolate chips in a spoonful of flour before folding them through — floured chips stay suspended instead of sinking to the bottom.',
      'Pour into a lined loaf tin and scatter a few more chips on top.',
      'Bake at 350°F for 55 to 60 minutes, covering the top with foil if it darkens too fast.',
      'Cool in the tin 15 minutes, then turn out. Slicing it hot makes it gummy.',
    ],
    macro: null, tagline: 'Chips That Stay Suspended', score: null, sc: null,
    diff: 'Medium', time: '1 hr 20 mins', extras: 'Chocolate Chips',
  },
  {
    id: 256, book: 2, secNum: 8, secName: CHOC,
    name: 'Chocolate Cream Pie',
    servings: '8 Servings', servN: 8,
    ing: ['1.5 cups white flour', '½ cup cold butter', '4 tbsp cold water', '1 tsp salt',
      '¾ cup sugar', '⅓ cup cocoa powder', '¼ cup cornstarch', '3 cups milk', '4 eggs',
      '2 tbsp butter', '2 tsp vanilla'],
    steps: [
      'Rub the cold butter into the flour and salt, add the water, and gather into a dough. Rest it 30 minutes in the fridge.',
      'Roll it out, line a pie dish, prick the base all over and line it with paper and baking weights.',
      'Bake blind at 400°F for 20 minutes, then remove the weights and bake 8 minutes more until dry and sand-coloured. A raw-bottomed cream pie is a sad thing.',
      'Whisk the sugar, cocoa, cornstarch and a pinch of salt in a pan, then whisk in the milk a little at a time so no lumps form.',
      'Cook over medium heat, whisking constantly, until it thickens and bubbles. Let it bubble a full minute — that is what cooks out the starch.',
      'Beat the egg yolks in a bowl, pour in a ladle of the hot mixture while whisking, then return it all to the pan.',
      'Cook 2 minutes more, still whisking, then take off the heat and stir in the butter and vanilla.',
      'Pour into the cooled crust and press plastic wrap directly onto the surface so no skin forms.',
      'Chill at least 4 hours before cutting.',
    ],
    macro: null, tagline: 'No Skin, No Soggy Bottom', score: null, sc: null,
    diff: 'In-Depth', time: '5 hrs 30 mins', extras: 'Cocoa Powder, Cornstarch',
  },
  {
    id: 257, book: 2, secNum: 8, secName: CHOC,
    name: 'Salted Chocolate Chip Cookie Bars',
    servings: '16 Bars', servN: 16,
    ing: ['¾ cup butter', '1 cup brown sugar', '½ cup sugar', '2 eggs', '2 tsp vanilla',
      '2 cups white flour', '1 tsp baking soda', '1 tsp salt', '1.5 cups chocolate chips'],
    steps: [
      'Melt the butter and let it cool for 5 minutes. Melted rather than creamed butter is what makes these chewy instead of cakey.',
      'Beat in both sugars, then the eggs and vanilla, and keep beating a minute until the mixture looks glossy.',
      'Fold in the flour, baking soda and salt just until combined.',
      'Fold through most of the chocolate chips.',
      'Press into a lined square pan and press the remaining chips into the top.',
      'Sprinkle the top with a little coarse salt.',
      'Bake at 350°F for 25 to 28 minutes, until the edges are golden and the middle is barely set.',
      'Cool completely in the pan before cutting — warm, they fall apart.',
    ],
    macro: null, tagline: 'Chewy, Not Cakey', score: null, sc: null,
    diff: 'Medium', time: '50 mins', extras: 'Chocolate Chips',
  },
];
