/*
 * The QR code on the printed books.
 *
 * Generated here rather than in the app, and written out as a finished SVG
 * path. Three reasons, in order of how much they matter:
 *
 *   It must not be fetched. Every other thing these pages need is in this
 *   repository — the typefaces, the engravings, the recipes — precisely so a
 *   page cannot arrive with a hole in it. A QR code served from an image API
 *   would be the one part of a printed book that depended on somebody else's
 *   uptime at the moment of rendering.
 *
 *   It must not cost the app anything. A QR encoder is a Reed-Solomon
 *   implementation and a mask-pattern search; shipping one to a phone so it can
 *   redraw a fixed URL on every render is the wrong trade. This runs once, when
 *   the URL changes, which is approximately never.
 *
 *   It must be a path, not a grid of rects. 1089 module squares is 1089 SVG
 *   elements per cover, in a document that already holds 160 pages of type. One
 *   path draws the same marks.
 *
 * Error correction is M rather than L. A book gets thumbed, folded back and set
 * down in flour; M tolerates about 15% of the symbol being lost, against L's 7%,
 * and costs four modules of resolution. That is the right way round for paper.
 *
 * Run:  node tools/build-qr.js
 */

const fs = require('fs');
const path = require('path');
const qrcode = require('qrcode-generator');

/* The landing page rather than the app itself. Someone scanning this is
   holding the book and has never seen the app; /welcome/ tells them what it is
   and how to put it on a home screen, and its first button opens the app. */
const URL = 'https://blakemerrell.github.io/storehouse-recipes/welcome/';

const q = qrcode(0, 'M');
q.addData(URL);
q.make();

const n = q.getModuleCount();

/* One path, one rectangle per dark module, drawn in the 0..n grid so the SVG
   can be scaled by its viewBox and never carries a pixel size of its own. */
let d = '';
for (let r = 0; r < n; r++) {
  for (let c = 0; c < n; c++) {
    if (q.isDark(r, c)) d += 'M' + c + ' ' + r + 'h1v1h-1z';
  }
}

/* A quiet zone of four modules is part of the specification, not a margin — a
   symbol printed hard against a rule or a page edge is one a phone will hunt
   for and often miss. It is in the viewBox so it cannot be laid out away. */
const Q = 4;
const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' +
  (-Q) + ' ' + (-Q) + ' ' + (n + Q * 2) + ' ' + (n + Q * 2) + '" ' +
  'shape-rendering="crispEdges" role="img" aria-label="Scan for the app">' +
  '<path fill="#fff" d="M' + (-Q) + ' ' + (-Q) + 'h' + (n + Q * 2) + 'v' + (n + Q * 2) + 'H' + (-Q) + 'z"/>' +
  '<path fill="#3b3630" d="' + d + '"/>' +
  '</svg>';

const out = '/* Generated by tools/build-qr.js — do not edit by hand.\n' +
  ' * ' + URL + '\n' +
  ' * ' + n + '×' + n + ' modules, error correction M, four-module quiet zone.\n' +
  ' */\n' +
  'window.APP_QR = ' + JSON.stringify(svg) + ';\n' +
  'window.APP_QR_URL = ' + JSON.stringify(URL) + ';\n';

fs.writeFileSync(path.join(__dirname, '..', 'data', 'qr.js'), out);
console.log('wrote data/qr.js  (' + n + '×' + n + ' modules, ' +
  (svg.length / 1024).toFixed(1) + ' KB)  ->  ' + URL);
